### PR TITLE
feat: Azure location override

### PR DESCRIPTION
**Pull request by jribble**
This adds an optional azure_location variable to specify which Azure location resources should be created in. I needed this when I decided I wanted everything created in a different location than I had created my resource group.

### CODE REVIEW

**Comment by jribble** [comment]
I just noticed the comments about the commit prefix in my earlier PR. I'm going to have to go figure out how that works....

**Comment by jribble** [comment]
From what I can tell I just need to add the prefix to the PR title. I did that. Let me know if I needed something else.

**Comment by atiterlea** [comment]
I checked the code for the action and there's a check for whether the PR has a single commit and, if so, it requires that the commit also contain the prefix.

**Comment by jribble** [comment]
This PR has 3 commits. Do I need to squash and modify the comment or is it good as is?

**Comment by atiterlea** [comment]
This check only applies to PRs with single commits, so just leave it as is.

**Comment by atiterlea** [comment]
I'd say the code changes look good. Can you elaborate on why this change is necessary? Why not create another resource group to match the region into which you'd like to deploy?

**Comment by jribble** [comment]
In my case I had assumed this feature would be there and I had already manually created the keystore, network and a bastion host in the resource group but in the correct location. This seemed easier than moving or recreating those.

**Review by atiterlea — APPROVED** [review]

**Pull request merged**
